### ISSUE TITLE
No implementation found for showAutocomplete()

### ISSUE THREAD

**Issue by GroovinChip** [derTuca/flutter_google_places_picker#1]
`var place = await PluginGooglePlacePicker.showAutocomplete(PlaceAutocompleteMode.MODE_OVERLAY);`

Android Studio finds no issue with this line, and the code autocomplete finds the method. However, when I click a button in my code to launch the places picker, I get the following error:

```
MissingPluginException(No implementation found for method showAutocomplete on channel plugin_google_place_picker)
E/flutter ( 1699): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:278:7)
E/flutter ( 1699): <asynchronous suspension>
E/flutter ( 1699): #1      PluginGooglePlacePicker.showAutocomplete (package:google_places_picker/google_places_picker.dart:32:41)
E/flutter ( 1699): <asynchronous suspension>

```
I have been having a very hard time finding a Places plugin that works, so if you could please look into this ASAP I would really appreciate it.

**Comment by derTuca** [comment]
I am going to clean up the old issues. If you still encounter issues, don't hesitate to open a new issue!
