### ISSUE TITLE
API project is not authorized

### ISSUE THREAD

**Issue by guyzk** [derTuca/flutter_google_places_picker#13]
Using the v2.0.0 of the plugin I get the following exception (on android).

`This API project is not authorized to use this API. Please ensure this API is activated in the Google Developers Console: https://console.developers.google.com/apis/api/places_backend?project=_`

Checked and double checked that all api's are enabled in the google cloud platform...
Anything I'm missing?

**Comment by erf** [comment]
Try to remove the `Podfile.lock` and `pods` folder, and reinstall pods for latest version. Also enable billing and restriction for credentials / api keys.

**Comment by guyzk** [comment]
> Try to remove the `Podfile.lock` and `pods` folder, and reinstall pods for latest version. Also enable billing and restriction for credentials / api keys.

Podfile? The issue is with Android.
Regarding the other settings. 
Billing is set but I haven't put any restrictions as I am still in the testing phase...
Are you talking about api restrictions? Which restriction should be set? Places Api or Places Android SDK?

**Comment by erf** [comment]
Oh ok. You could try to reinstall Places SDK for Android ( if this is not done automatically ). I'm talking about credentials restrictions for Android mobile only. Not sure this solves anything, just a suggestion to try.
