### ISSUE TITLE
Severe bug: Places picker leads to crash of image picker on Android

### ISSUE THREAD

**Issue by msw333** [derTuca/flutter_google_places_picker#15]
When I am initializing my API token for the Places Picker (2.0.0), this leads to a crash of the official ImagePicker plugin in Android:

If you select to 'image source camera' and try to take the picture, the app crashes with the following error:

`D/AndroidRuntime( 1687): Shutting down VM
E/AndroidRuntime( 1687): FATAL EXCEPTION: main
E/AndroidRuntime( 1687): Process: com.example.firstapp, PID: 1687
E/AndroidRuntime( 1687): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2343, result=-1, data=null} to activity {com.example.firstapp/com.example.firstapp.MainActivity}: java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime( 1687): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5002)
E/AndroidRuntime( 1687): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5044)
E/AndroidRuntime( 1687): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
E/AndroidRuntime( 1687): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
E/AndroidRuntime( 1687): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
E/AndroidRuntime( 1687): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2155)
E/AndroidRuntime( 1687): 	at android.os.Handler.dispatchMessage(Handler.java:109)
E/AndroidRuntime( 1687): 	at android.os.Looper.loop(Looper.java:207)
E/AndroidRuntime( 1687): 	at android.app.ActivityThread.main(ActivityThread.java:7536)
E/AndroidRuntime( 1687): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 1687): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
E/AndroidRuntime( 1687): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
E/AndroidRuntime( 1687): Caused by: java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime( 1687): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:124)
E/AndroidRuntime( 1687): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.error(MethodChannel.java:209)
E/AndroidRuntime( 1687): 	at com.theantimony.googleplacespicker.GooglePlacesPickerPlugin.onActivityResult(GooglePlacesPickerPlugin.kt:156)
E/AndroidRuntime( 1687): 	at io.flutter.app.FlutterPluginRegistry.onActivityResult(FlutterPluginRegistry.java:222)
E/AndroidRuntime( 1687): 	at io.flutter.app.FlutterActivityDelegate.onActivityResult(FlutterActivityDelegate.java:142)
E/AndroidRuntime( 1687): 	at io.flutter.app.FlutterActivity.onActivityResult(FlutterActivity.java:142)
E/AndroidRuntime( 1687): 	at android.app.Activity.dispatchActivityResult(Activity.java:7794)
E/AndroidRuntime( 1687): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4995)
E/AndroidRuntime( 1687): 	... 11 more
I/Process ( 1687): Sending signal. PID: 1687 SIG: 9
Application finished.`

**Comment by derTuca** [comment]
Fixed in 2.0.1.
