### ISSUE TITLE
((null)) was false: provideAPIKey: should be called at most once

### ISSUE THREAD

**Issue by msw333** [derTuca/flutter_google_places_picker#16]
I get the following warning `((null)) was false: provideAPIKey: should be called at most once` when calling 

```
Future main() async {

  PluginGooglePlacePicker.initialize(
    androidApiKey: "**********************",
    iosApiKey: "*****************",
  );

  runApp(new ChatFish());
}
```

**Comment by derTuca** [comment]
I would suggest setting a breakpoint on `initialize` to verify whether it is called multiple times, and if it is, to remove later calls.
