### ISSUE TITLE
Compilation error in plugin's Kotlin code

### ISSUE THREAD

**Issue by abhinavc** [derTuca/flutter_google_places_picker#19]
Hi, 
I am seeing the following error during compilation. Seems to be in the plugin's code itself.
My local setup is 
- Dart 2.3.0
- Flutter 1.5.4-hotfix.2

```
kotlin/com/theantimony/googleplacespicker/GooglePlacesPickerPlugin.kt: (75, 46): 
Type mismatch: inferred type is String? but String was expected
```
If the fix is simple, then would it be possible to get a hotfix release? 

Thanks
Abhinav

**Comment by derTuca** [comment]
That's weird, Kotlin should be applying a Smart Cast automatically since I run `isNullOrEmpty()` beforehand. I added a forced cast in the latest version just in case, please reopen this issue if it does not work.
