### ISSUE TITLE
'Can only use lower 16 bits for requestCode' error on Android

### ISSUE THREAD

**Issue by graperaisin1** [derTuca/flutter_google_places_picker#23]
Using version 2.0.2+2 of the plugin and getting this error when tapping the field:

`Can only use lower 16 bits for requestCode`

Current request code in the plugin:

`const val PLACE_AUTOCOMPLETE_REQUEST_CODE = 131071`

Similar issues on StackOverflow suggest that the request code should be between 0 and 65535:
https://stackoverflow.com/questions/25529865/java-lang-illegalargumentexception-can-only-use-lower-16-bits-for-requestcode

Is there any current workaround?

**Comment by sergiomartell** [comment]
Having same problem.

**Comment by jacques13** [comment]
Any Solution yet ??

**Comment by derTuca** [comment]
Fixed in 2.1. Sorry for the delay.
