### ISSUE TITLE
UI Font Color not working properly in IOS Dark theme

### ISSUE THREAD

**Issue by SandyAra** [derTuca/flutter_google_places_picker#26]
![WhatsApp Image 2019-11-16 at 9 01 44 PM](https://user-images.githubusercontent.com/45088009/68995478-63387000-08b4-11ea-832d-e0eafa0a29fe.jpeg)

**Comment by Zeeshan0201** [comment]
@SandyAra facing same issue,have you find any solution?

**Comment by derTuca** [comment]
WAY overdue, but fixed in 3.0.2. Thank you for the report.
