### ISSUE TITLE
Conflict with other packages

### ISSUE THREAD

**Issue by niypoo** [derTuca/flutter_google_places_picker#27]
when use it with `flutter_background_geolocation` or `background_fetch` it's make others packages give me that error

> [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)

you can see last example in github here 
[https://github.com/transistorsoft/flutter_background_geolocation/issues/167](https://github.com/transistorsoft/flutter_background_geolocation/issues/167)

**Comment by tapsey** [comment]
Cause image_picker package to not work. Please call `super.onActivityResult`

**Comment by derTuca** [comment]
Please try 2.1.0+2.
