### ISSUE TITLE
Null Safety

### ISSUE THREAD

**Issue by benedictkhoo** [derTuca/flutter_google_places_picker#34]
Flutter 2 is now out and comes with null safety. Any plans to support them? Thanks!

**Comment by derTuca** [comment]
Hello! Yes, I will update this plugin to support it. I will do my best to do it by the end of this weekend, but if I don't get to then it will be done next week.

**Comment by benedictkhoo** [comment]
@derTuca awesome! Thanks! :)

**Comment by derTuca** [comment]
Released 3.0.0-nullsafety.0 to address this. If you find something wrong, please open another issue. Thanks!

**Comment by benedictkhoo** [comment]
Awesome! Thanks @derTuca for the hard work!
