### ISSUE TITLE
Press cancel but page did not close

### ISSUE THREAD

**Issue by hafizidev** [derTuca/flutter_google_places_picker#4]
In iOS, while clicking on the cancel button, page did not close while it does throw exception :

`PlatformException(USER_CANCELED, User has canceled the operation., null)`

![button](https://user-images.githubusercontent.com/36718405/48121099-feb10100-e2ae-11e8-8465-1e474551ab58.png)

Platforms affected
&#9745;  iOS
&#9744;  Android

**Comment by zxcvbnmmohd** [comment]
Also, when you tap cancel and search it doesn't select the selected address, it just comes out empty.

**Comment by derTuca** [comment]
Fixed in 0.1.0.
